### ISSUE TITLE
Allow user to choose different ORM with Nyara generator

### ISSUE THREAD

**Issue by huacnlee** [luikore/nyara#19]
```
nyara new xxx -d mysql
nyara new xxx -d mongoid
```

**Comment by luikore** [comment]
mysql is database driver, and mongoid is ORM.

We can provide commented database driver options in Gemfile, and make only options for ORM.

``` sh
nyara n xxx -o mongoid
nyara n xxx --orm mongoid
```

**Comment by hooopo** [comment]
Padrino 的 Components Agnostic Support 非常完善：
![](http://l.ruby-china.org/photo/2bcc6e75b25763c924b5df88fd9283d3.png)

嗯，还有一个--adapter参数指定driver。

**Comment by SaitoWu** [comment]
其实我觉得默认支持 postgres 就行了, mongoid 这种可以自己加.

不要提供那么多选项.

**Comment by hooopo** [comment]
@SaitoWu Omakase Stack V5!

**Comment by luikore** [comment]
写了一半发现分离 orm 和 driver 是自己找麻烦... 就一个 database.yml 而已

**Comment by luikore** [comment]
Comakase

``` sh
nyara new xxx -t slim -o activerecord
```

Nomakase

``` sh
nyara new xxx -o none
```

Admakase

``` sh
nyara g database.yml -o activerecord
```

**Comment by luikore** [comment]
- [x] when activerecord is chosen, add `rake db:*` tasks
