### ISSUE TITLE
Views 的内容无法自动 reload

### ISSUE THREAD

**Issue by huacnlee** [luikore/nyara#20]
不知道是不是还没有实现，每次修改都得重启一下...

**Comment by luikore** [comment]
实现了, 不过可能没测试对... 我查一下

**Comment by huacnlee** [comment]
应该是 Nyara::Reload.listen 目前没有加到项目启动中，另外我加上了以后发现 View 还是没法自动  reload

**Comment by luikore** [comment]
view 已经可以 reload, 另外 reload 后出错就不能继续 reload 是因为 curl 卡住了... 已经于 https://github.com/luikore/nyara/commit/082eea7ab4373d37e95419616269f6f999293774 修正

**Comment by huacnlee** [comment]
顶

Jason Lee
http://huacnlee.com
http://twitter.com/huacnlee

在 2013年8月16日，1:53，Zete notifications@github.com 写道：

view 已经可以 reload, 另外 reload 后出错就不能继续 reload 是因为 curl 卡住了... 已经于
082eea7https://github.com/luikore/nyara/commit/082eea7ab4373d37e95419616269f6f999293774修正

—
Reply to this email directly or view it on
GitHubhttps://github.com/luikore/nyara/issues/20#issuecomment-22717122
.
