### ISSUE TITLE
Add instruction of command `server` when do 'nyara help'

### ISSUE THREAD

**Issue by nevill** [luikore/nyara#26]
As a newbie, it's hard for me to know how to start the generated application.

Please add it. :)

**Comment by huacnlee** [comment]
``` bash
nyara new xxx
```

https://github.com/luikore/nyara/wiki/Manual#project-structure

**Comment by nevill** [comment]
@huacnlee  thank you, your commit d77f3e5e2d9e7745734f29253e562685b0d83a8a fixed it.
Also, `rake console` is added, manual is updated, awesome.
